vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix:  '%app.path.image%'
            upload_destination: '%kernel.project_dir%/public%app.path.image%'
            namer: vich_uploader.namer_origname
            delete_on_update: true
            delete_on_remove: true
